import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import DesktopSidebar from "@/components/ui/dasboard/DesktopSidebar";
import DeskTopRecommendationBar from "@/components/ui/dasboard/DeskTopRecomBar";
import PhoneSidebar from "@/components/ui/dasboard/PhoneSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SymptoCheck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <div className="flex h-screen">
      <DesktopSidebar />
      <PhoneSidebar/>
      <main className="flex-1 overflow-y-auto">{children}</main>
      <DeskTopRecommendationBar/>
    </div>
  </body>
</html>

  );
}
